apiVersion: apps/v1
kind: Deployment
metadata:
  name: str-api-com-app
  labels:
    app: str-api-com
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      enabled: true
      maxUnavailable: 0
      maxSurge: "100%"
  selector:
    matchLabels:
      app: str-api-com
  template:
    metadata:
      labels:
        app: str-api-com
        myapp: delete-me  # Label for deletion
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: str-api-com
        image: {{.Values.apialphaimage}}
        envFrom:
          - secretRef:
              name: alpha-secrets-prod
        # rollingUpdate:
        #   enabled: true
        #   maxSurge: "100%"
        #   maxUnavailable: "50%"
        ports:
        - name: str-api-port
          containerPort: 80
          # envFrom:
          # - secretRef:
          #     name: alphaasec
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health-check.php  
            port: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 20"]
          initialDelaySeconds: 5  # Delay before the first probe
          periodSeconds: 1  # How often we want to perform the probe
