apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  
    name: api-core
  minReplicas: 4    
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  #metrics:
  #- type: Resource
    #resource:
      #name: cpu
      #targetAverageUtilization: 50  # Target CPU utilization percentage
      #targetAverageValue: "100m"   # Target CPU request (100 milliCPU)
